DatabaseLabWeb2/Controllers/dbHLController.cs
using DatabaseLabWeb2.Controllers.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MongoDB.Driver;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DatabaseLabWeb2.Controllers
{
    public class dbHLController : Controller
    {
        private readonly ILogger<dbHLController> _logger;
        public dbHLController(ILogger<dbHLController> logger)
        {
            _logger = logger;
        }

        public static IMongoDatabase db;
        public class MongoCRUD
        {
            public MongoCRUD(string database)
            {
                var client = new MongoClient("mongodb+srv://andlek1:andlek1@db1.dtfyj.mongodb.net/DB1?authSource=admin&replicaSet=atlas-jww9tl-shard-0&readPreference=primary&appname=MongoDB%20Compass&ssl=true");
                db = client.GetDatabase(database);
            }
        }

        public IActionResult Index()
        {
            MongoCRUD dbHL = new MongoCRUD("DB22");
            var collection = db.GetCollection<JobMaterial>("job_materials");
            List<JobMaterial> job_materialsCollection = collection.AsQueryable<JobMaterial>().ToList();
            return View(job_materialsCollection.Where(x=> x.quantity < 50).ToList());
        }
    }
}

DatabaseLabWeb2/Controllers/dbHuController.cs
using DatabaseLabWeb2.Controllers.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MongoDB.Driver;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DatabaseLabWeb2.Controllers
{
    public class dbHuController : Controller
    {
        private readonly ILogger<dbHuController> _logger;
        public dbHuController(ILogger<dbHuController> logger)
        {
            _logger = logger;
        }
        public static IMongoDatabase db;
        public class MongoCRUD
        {
            public MongoCRUD(string database)
            {
                var client = new MongoClient("mongodb+srv://andlek1:andlek1@db1.dtfyj.mongodb.net/DB1?authSource=admin&replicaSet=atlas-jww9tl-shard-0&readPreference=primary&appname=MongoDB%20Compass&ssl=true");
                db = client.GetDatabase(database);
            }
        }
        public IActionResult Index()
        {
            MongoCRUD dbHu = new MongoCRUD("DB33");
            var collection = db.GetCollection<JobMaterial>("job_materials");
            List<JobMaterial> job_materialsCollection = collection.AsQueryable<JobMaterial>().ToList();
            return View(job_materialsCollection.Where(x=> x.quantity >= 50).ToList());
        }
    }
}

DatabaseLabWeb2/Controllers/dbV1Controller.cs
using DatabaseLabWeb2.Controllers.Models;
using DatabaseLabWeb2.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MongoDB.Driver;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DatabaseLabWeb2.Controllers
{
    public class dbV1Controller : Controller
    {
        private readonly ILogger<dbV1Controller> _logger;
        public dbV1Controller(ILogger<dbV1Controller> logger)
        {
            _logger = logger;
        }

        public static IMongoDatabase db;
        public class MongoCRUD
        {
            public MongoCRUD(string database)
            {
                var client = new MongoClient("mongodb+srv://andlek1:andlek1@db1.dtfyj.mongodb.net/DB1?authSource=admin&replicaSet=atlas-jww9tl-shard-0&readPreference=primary&appname=MongoDB%20Compass&ssl=true");
                db = client.GetDatabase(database);
            }
        }
        public IActionResult Index()
        {
            MongoCRUD dbV1 = new MongoCRUD("DB2");
            var collection = db.GetCollection<ProjectV1>("projects");
            List<ProjectV1> projectCollection = collection.AsQueryable<ProjectV1>().ToList();
            return View(projectCollection);
        }
    }
}

DatabaseLabWeb2/Controllers/dbV2Controller.cs
using DatabaseLabWeb2.Controllers.Models;
using DatabaseLabWeb2.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MongoDB.Driver;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DatabaseLabWeb2.Controllers
{
    public class dbV2Controller : Controller
    {
        private readonly ILogger<dbV2Controller> _logger;
        public dbV2Controller(ILogger<dbV2Controller> logger)
        {
            _logger = logger;
        }

        public static IMongoDatabase db;
        public class MongoCRUD
        {
            public MongoCRUD(string database)
            {
                var client = new MongoClient("mongodb+srv://andlek1:andlek1@db1.dtfyj.mongodb.net/DB1?authSource=admin&replicaSet=atlas-jww9tl-shard-0&readPreference=primary&appname=MongoDB%20Compass&ssl=true");
                db = client.GetDatabase(database);
            }
        }
        public IActionResult Index()
        {
            MongoCRUD dbV2 = new MongoCRUD("DB3");
            var collection = db.GetCollection<ProjectV2>("projects");
            List<ProjectV2> projectCollection = collection.AsQueryable<ProjectV2>().ToList();
            return View(projectCollection);
        }
      
    }
}

DatabaseLabWeb2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DatabaseLabWeb2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">DB_Projects_Bendra</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home2" asp-action="Index">DB_Job_Materials_Bendra</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="dbHL" asp-action="Index">DB_HL</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="dbHu" asp-action="Index">DB_HU</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="dbV1" asp-action="Index">DB_V1</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="dbV2" asp-action="Index">DB_V2</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - DatabaseLabWeb2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>